# Generated by Django 3.0.5 on 2020-05-21 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import regabitur.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pub', models.DateTimeField(auto_now=True)),
                ('name_doc', models.CharField(choices=[('Заявление', 'Заявление'), ('Заявление доп', 'Заявление: еще страница'), ('Учетная карточка', 'Учетная карточка'), ('Учетная карточка доп', 'Учетная карточка: еще страница'), ('Согласие на зачисление', 'Согласие на зачисление'), ('Согласие на зачисление доп', 'Согласие на зачисление: еще страница'), ('Обработка персональных данных', 'Обработка персональных данных'), ('Обработка персональных данных доп', 'Обработка персональных данных: еще страница'), ('Фото (3х4)', 'Фото (3х4)'), ('Документ, удостоверяющий личность', 'Документ, удостоверяющий личность'), ('Документ, удостоверяющий личность доп', 'Документ, удостоверяющий личность: еще страница'), ('Временная регистрация', 'Временная регистрация(при наличии в СПб)'), ('Документ об образовании', 'Документ об образовании'), ('Документ об образовании доп', 'Документ об образовании: еще страница'), ('мед.справка', 'Медицинская справка по форме 086-У'), ('мед.справка доп.', 'Медицинская справка по форме 086-У: еще страница'), ('Прививочный сертификат', 'Прививочный сертификат'), ('Прививочный сертификат доп', 'Прививочный сертификат: еще страница'), ('Военный билет или приписное', 'Военный билет или приписное удостоверение'), ('Военный билет или приписное доп', 'Военный билет или приписное удостоверение: еще страница'), ('Снилс', 'Снилс'), ('Снилс доп', 'Снилс: еще страница'), ('Индивидуальные достижения', 'Индивидуальные достижения'), ('Индивидуальные достижения доп', 'Индивидуальные достижения: еще страница')], max_length=256, verbose_name='Название документа')),
                ('doc', models.FileField(upload_to=regabitur.models.user_directory_path, verbose_name='Загрузить документ')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Абитуриент')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('patronymic', models.CharField(default='', max_length=80, verbose_name='Отчество')),
                ('phone_number', models.CharField(default='', max_length=15, verbose_name='Номер телефона')),
                ('sending_status', models.CharField(choices=[('error', 'Вероятно, вы указали неверные данные электронной почты или номер телефона. Пожалуйста, свяжитесь с сотрудниками академии по телефону'), ('no', 'Документы не поданы'), ('send', 'Документы отправлены и ждут обработки сотрудниками приемной комисси'), ('working', 'Документы находятся в обработке'), ('success', 'Документы обработаны и приняты')], default='no', max_length=256, verbose_name='Статус заявки')),
                ('complete_flag', models.BooleanField(default=False, verbose_name='Документы отправлены?:')),
                ('agreement_flag', models.BooleanField(default=False, verbose_name='Соглашение:')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='custom', to=settings.AUTH_USER_MODEL, verbose_name='Абитуриент')),
            ],
        ),
    ]
