# Generated by Django 3.0.5 on 2020-05-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Абитуриент', 'verbose_name_plural': 'Абитуриента'},
        ),
        migrations.AlterModelOptions(
            name='documentuser',
            options={'verbose_name': 'Документы абитуриентов', 'verbose_name_plural': 'Документы абитуриентов'},
        ),
    ]
