# Generated by Django 3.1.3 on 2021-02-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0005_customuser_success_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sending_status',
            field=models.CharField(choices=[('error', 'Вероятно, вы указали неверные данные электронной почты или номер телефона. Пожалуйста, свяжитесь с сотрудниками академии по телефону'), ('no', 'Документы не поданы'), ('send', 'Документы отправлены и ждут обработки сотрудниками приемной комисси'), ('working', 'Документы находятся в обработке'), ('success', 'Документы обработаны и приняты'), ('back', 'Документы отозваны')], default='no', max_length=256, verbose_name='Статус заявки'),
        ),
    ]
