# Generated by Django 3.1.3 on 2021-04-05 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regabitur', '0006_auto_20210205_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Профиль обучения',
                'verbose_name_plural': 'Профили обучения',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='comment_admin',
            field=models.TextField(blank=True, verbose_name='Комментарий для внутренней работы'),
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=' ', max_length=400, verbose_name='Адрес прописки')),
                ('individual_str', models.CharField(blank=True, max_length=32)),
                ('education_profile', models.ManyToManyField(to='regabitur.ChoicesProfile')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Дополнительно')),
            ],
        ),
    ]
