# Generated by Django 3.1.3 on 2021-04-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0008_auto_20210408_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinfo',
            name='individual_str',
        ),
    ]
