# Generated by Django 3.1.3 on 2021-04-12 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regabitur', '0009_remove_additionalinfo_individual_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='education_profile',
            field=models.ManyToManyField(to='regabitur.ChoicesProfile', verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='addition', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
