# Generated by Django 3.1.3 on 2021-04-13 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regabitur', '0010_auto_20210412_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinfo',
            options={'verbose_name': 'Выбранные профили обучения', 'verbose_name_plural': 'Выбранные профили обучения'},
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='addition', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
