# Generated by Django 3.2.3 on 2021-06-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0012_alter_publishtab_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishtab',
            old_name='bac_ofo',
            new_name='bak_ofo_gp',
        ),
        migrations.RenameField(
            model_name='publishtab',
            old_name='bac_ozfo',
            new_name='bak_ozfo_sd',
        ),
        migrations.RenameField(
            model_name='publishtab',
            old_name='bac_zfo',
            new_name='bak_zfo_up',
        ),
    ]
