# Generated by Django 3.2.3 on 2021-06-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0013_auto_20210611_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentuser',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=400, verbose_name='Адрес прописки'),
        ),
        migrations.AddField(
            model_name='documentuser',
            name='passport',
            field=models.CharField(blank=True, default=' ', max_length=20, verbose_name='Паспортные данные(серия-номер)'),
        ),
        migrations.AddField(
            model_name='documentuser',
            name='snils',
            field=models.CharField(blank=True, default=' ', max_length=32, verbose_name='Номер снился'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=400, verbose_name='Адрес прописки'),
        ),
    ]
