# Generated by Django 3.2.3 on 2021-06-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0015_auto_20210616_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinfo',
            name='address',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=400, verbose_name='Адрес прописки (по паспорту)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='snils',
            field=models.CharField(blank=True, default=' ', max_length=32, verbose_name='Номер снилса'),
        ),
    ]
