# Generated by Django 3.2.3 on 2021-06-28 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regabitur', '0018_auto_20210618_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='message',
            field=models.CharField(blank=True, default=' ', max_length=512, verbose_name='Сообщение от приемной коммисии'),
        ),
        migrations.AlterField(
            model_name='publishtab',
            name='individual_str',
            field=models.CharField(blank=True, default='34/21-', max_length=32, verbose_name="Год/поток (после значения не забудьте поставить знак '-'"),
        ),
        migrations.AlterField(
            model_name='publishtab',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='publish', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
