# Generated by Django 3.2.3 on 2021-07-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0018_auto_20210619_1117'),
        ('regabitur', '0019_auto_20210628_0833'),
    ]

    operations = [
    ]
