# Generated by Django 3.2.5 on 2021-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0020_auto_20210713_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishrectab',
            name='gp_point',
        ),
        migrations.RemoveField(
            model_name='publishrectab',
            name='okp_point',
        ),
        migrations.RemoveField(
            model_name='publishrectab',
            name='tgp_point',
        ),
        migrations.RemoveField(
            model_name='publishrectab',
            name='up_point',
        ),
        migrations.RemoveField(
            model_name='publishrectab',
            name='vstupit_bak_ofo_gp',
        ),
        migrations.RemoveField(
            model_name='publishrectab',
            name='vstupit_bak_ofo_up',
        ),
        migrations.RemoveField(
            model_name='publishrectab',
            name='vstupit_bak_ozfo_gp',
        ),
        migrations.RemoveField(
            model_name='publishrectab',
            name='vstupit_bak_ozfo_up',
        ),
        migrations.RemoveField(
            model_name='publishrectab',
            name='vstupit_bak_zfo_gp',
        ),
        migrations.RemoveField(
            model_name='publishrectab',
            name='vstupit_bak_zfo_up',
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='advantage',
            field=models.CharField(blank=True, max_length=256, verbose_name='Преимущественное право'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='choice_ege_point',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name=' ЕГЭ История / Английский'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='choice_vstupit_point',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='История/ТГП/ОКП'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='gpup_point',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='ГП/УП'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='individ',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Индивид. достижения'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='sogl',
            field=models.BooleanField(default=False, verbose_name='Согласие на зачисление'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='sost_type',
            field=models.CharField(choices=[('Рекомендован', 'Рекомендован'), ('Не рекомендован', 'Не рекомендован')], default=('Рекомендован', 'Рекомендован'), max_length=256, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='sum_points',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Сумма баллов'),
        ),
        migrations.AlterField(
            model_name='publishrectab',
            name='obsh_point',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Обществознание'),
        ),
        migrations.AlterField(
            model_name='publishrectab',
            name='rus_point',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Конст. Право РФ'),
        ),
        migrations.AlterField(
            model_name='publishrectab',
            name='spec_point',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Спец. дисциплина (Асп)'),
        ),
    ]
