# Generated by Django 3.2.5 on 2021-07-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0021_auto_20210713_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishrectab',
            name='kp_point',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Конст. Право РФ'),
        ),
        migrations.AlterField(
            model_name='publishrectab',
            name='rus_point',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Русский язык'),
        ),
    ]
