# Generated by Django 3.2.5 on 2021-07-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0022_auto_20210713_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishrectab',
            options={'verbose_name': 'Опубликовать в списки ромендованных к зачислению', 'verbose_name_plural': 'Опубликовать в списки ромендованных к зачислению'},
        ),
        migrations.AlterField(
            model_name='publishrectab',
            name='sogl',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default=('Да', 'Да'), max_length=256, verbose_name='Согласие на зачисление'),
        ),
    ]
