# Generated by Django 3.2.5 on 2021-07-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0023_auto_20210713_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishrectab',
            name='advantage',
            field=models.CharField(blank=True, choices=[('Имеет', 'Имеет'), ('Не имеет', 'Не имеет')], default=('Не имеет', 'Не имеет'), max_length=256, verbose_name='Преимущественное право'),
        ),
        migrations.AlterField(
            model_name='publishrectab',
            name='sogl',
            field=models.CharField(choices=[('Подано', 'Подано'), ('Не подано', 'Не подано')], default=('Не подано', 'Не подано'), max_length=256, verbose_name='Согласие на зачисление'),
        ),
    ]
