# Generated by Django 3.2.5 on 2021-07-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0020_merge_0018_auto_20210619_1117_0019_auto_20210628_0833'),
        ('regabitur', '0024_auto_20210713_1238'),
    ]

    operations = [
    ]
