# Generated by Django 3.2.5 on 2021-07-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0025_merge_20210715_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishrectab',
            options={'ordering': ['-sum_points'], 'verbose_name': 'Опубликовать в списки ромендованных к зачислению', 'verbose_name_plural': 'Опубликовать в списки ромендованных к зачислению'},
        ),
    ]
