# Generated by Django 3.2.5 on 2021-07-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0026_alter_publishrectab_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishrectab',
            name='bak_zfo_gp',
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='asp_ofo_ks',
            field=models.BooleanField(default=False, verbose_name='АСП ОФО Криминалистика'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='asp_ofo_tip',
            field=models.BooleanField(default=False, verbose_name='АСП ОФО Теор. и истор.'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='asp_ofo_up',
            field=models.BooleanField(default=False, verbose_name='АСП ОФО Уголовный проц.'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='asp_zfo_ks',
            field=models.BooleanField(default=False, verbose_name='АСП ЗФО Криминалистика'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='asp_zfo_tip',
            field=models.BooleanField(default=False, verbose_name='АСП ЗФО Теор. и истор.'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='asp_zfo_up',
            field=models.BooleanField(default=False, verbose_name='АСП ЗФО Уголовный проц'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='mag_ofo_po',
            field=models.BooleanField(default=False, verbose_name='МАГ ОФО Прав. обеспеч.'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='mag_ofo_tp',
            field=models.BooleanField(default=False, verbose_name='МАГ ОФО Теор. и практ.'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='mag_zfo_po',
            field=models.BooleanField(default=False, verbose_name='МАГ ЗФО Прав. обеспеч.'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='mag_zfo_tp',
            field=models.BooleanField(default=False, verbose_name='МАГ ЗФО Теор. и практ.'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='spec_ofo_sd',
            field=models.BooleanField(default=False, verbose_name='СПЕЦ ОФО СПД'),
        ),
        migrations.AlterField(
            model_name='publishrectab',
            name='bak_ofo_gp',
            field=models.BooleanField(default=False, verbose_name='БАК ОФО ГП'),
        ),
        migrations.AlterField(
            model_name='publishrectab',
            name='bak_ofo_up',
            field=models.BooleanField(default=False, verbose_name='БАК ОФО УП'),
        ),
        migrations.AlterField(
            model_name='publishrectab',
            name='bak_ozfo_gp',
            field=models.BooleanField(default=False, verbose_name='БАК ОЗФО ГП'),
        ),
        migrations.AlterField(
            model_name='publishrectab',
            name='bak_ozfo_up',
            field=models.BooleanField(default=False, verbose_name='БАК ОЗФО УП'),
        ),
        migrations.AlterField(
            model_name='publishrectab',
            name='bak_zfo_up',
            field=models.BooleanField(default=False, verbose_name='БАК ЗФО УП'),
        ),
    ]
