# Generated by Django 3.2.5 on 2021-07-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0028_auto_20210715_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishrectab',
            name='sogl',
            field=models.CharField(choices=[('Подано', 'Подано'), ('Не подано', 'Не подано'), ('Отозвано', 'Отозвано')], default=('Не подано', 'Не подано'), max_length=256, verbose_name='Согласие на зачисление'),
        ),
    ]
