# Generated by Django 3.2.5 on 2022-01-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0029_alter_publishrectab_sogl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishrectab',
            name='choice_ege_point',
        ),
        migrations.RemoveField(
            model_name='publishrectab',
            name='choice_vstupit_point',
        ),
        migrations.RemoveField(
            model_name='publishrectab',
            name='gpup_point',
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='foreign_language_point',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Иностранный язык'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='gp_point',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='ГП'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='history_point',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='История'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='tgp_point',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='ТГП'),
        ),
        migrations.AddField(
            model_name='publishrectab',
            name='up_point',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='УП'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='message',
            field=models.TextField(blank=True, default=' ', verbose_name='Сообщение от приемной комисии'),
        ),
    ]
