# Generated by Django 3.2.5 on 2022-01-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regabitur', '0030_auto_20220120_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishrectab',
            name='okp_point',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='ОКП'),
        ),
    ]
