# Generated by Django 3.1.3 on 2021-02-05 10:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abitur', '0005_auto_20200602_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, default='pictures/base.jpg', max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/home/oleg/abiturient/myproject/uploads'), upload_to='image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='newsfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/home/oleg/abiturient/myproject/uploads'), upload_to='files', verbose_name='Прикрепить файл'),
        ),
    ]
