# Generated by Django 3.2.3 on 2021-06-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abitur', '0006_auto_20210205_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitdocasp',
            name='educational_form',
        ),
        migrations.RemoveField(
            model_name='submitdocmag',
            name='educational_form',
        ),
        migrations.DeleteModel(
            name='SubmitDoc',
        ),
        migrations.DeleteModel(
            name='SubmitDocAsp',
        ),
        migrations.DeleteModel(
            name='SubmitDocMag',
        ),
    ]
