# Generated by Django 3.2.5 on 2021-07-27 09:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abitur', '0007_auto_20210619_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, default='pictures/base.jpg', max_length=255, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/home/oleg/PycharmProjects/abiturient/myproject/uploads'), upload_to='image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='newsfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='/home/oleg/PycharmProjects/abiturient/myproject/uploads'), upload_to='files', verbose_name='Прикрепить файл'),
        ),
    ]
